url: http://eternalistic.net
name: Jeremy Caldwell
author: Jeremy Caldwell

markdown: redcarpet
pygments: true
paginate: 5

root: /
permalink: /:year/:month/:title/

#GitHub Overrides
safe: true
lsi: false
pygments: true