url: http://www.eternalistic.net
name: Jeremy Caldwell
author: Jeremy Caldwell

# markdown: redcarpet



kramdown:
  use_coderay: true

maruku:
  use_divs:   true








paginate: 5

root: /
permalink: /:year/:month/:title/

exclude: [Gemfile, Gemfile.lock, inspiration.txt, Gruntfile.js, package.json, node_modules, sass, script.js, production.js]

#GitHub Overrides
safe: false
lsi: false




prose:
  siteurl: "http://eternalistic.github.io"
  media: "images"
  metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
      - name: "layout"
        field:
          label: "Layout"
          element: "text"
          value: "post"
      - name: "title"
        field:
          label: "Title"
          element: "text"
          value: "A awesome Headline!"