url: http://www.eternalistic.net
name: Jeremy Caldwell
author: Jeremy Caldwell

# markdown: redcarpet
markdown: kramdown
kramdown:
  use_coderay: true



paginate: 5

root: /
permalink: /:year/:month/:title/

exclude: [Gemfile, Gemfile.lock, inspiration.txt, Gruntfile.js, package.json, node_modules, sass, script.js, production.js]

#GitHub Overrides
safe: false
lsi: false
pygments: true