url: http://www.eternalistic.net
name: Jeremy Caldwell
author: Jeremy Caldwell


# Editor
markdown: redcarpet
pygments: true


# Disqus
disqus:
    shortname: 'eternalisticblog'


# Post
post:
  extension: md
paginate: 5
root: /
permalink: /:year/:month/:title/


# Exclude
exclude: [Gemfile, Gemfile.lock, inspiration.txt, Gruntfile.js, package.json, node_modules, sass, script.js, production.js]


# GitHub Overrides
safe: false
lsi: false


# Prose
prose:
  siteurl: "http://eternalistic.github.io"
  media: "images"
  metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
      - name: "layout"
        field:
          label: "Layout"
          element: "text"
          value: "post"
      - name: "title"
        field:
          label: "Title"
          element: "text"
          value: "A awesome Headline!"

